source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

xcodeproj 'Deviice'
use_frameworks!

target 'Deviice_Example' do
  pod 'Deviice', :path => '../'
end


target 'Deviice_Tests' do
  pod 'Deviice', :path => '../'
end
